boards: arc: qemu: Move arch selection from defconfig to SoC
On configuration we saw:
------------------------->8----------------------
error: ARC (defined at arch/Kconfig:19) is assigned in a configuration
file, but is not directly user-configurable (has no prompt).

It gets its value indirectly from other symbols.
------------------------->8----------------------

That's because of upstream change done by
commit c5839f834b30 ("kconfig: Remove assignments to CONFIG_<arch> syms and hide them")

Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>